spring:
  profiles:
    active: ${SPRING_PROFILE}
  application:
    name: Sudoku Journey
  security:
    oauth2:
      resourceserver:
        opaque-token:
          google:
            introspect-uri: https://www.googleapis.com
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

firebase:
  service:
    account:
      keys:
        type: "service_account"
        project_id: ${PROJECT_ID}
        private_key_id: ${PRIVATE_KEY_ID}
        private_key: ${PRIVATE_KEY}
        client_email: "firebase-adminsdk-sibxb@hidden-moon-431916-h2.iam.gserviceaccount.com"
        client_id: ${CLIENT_ID}
        auth_uri: "https://accounts.google.com/o/oauth2/auth"
        token_uri: "https://oauth2.googleapis.com/token"
        auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
        client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-sibxb%40hidden-moon-431916-h2.iam.gserviceaccount.com"
        universe_domain: "googleapis.com"